name: dagger

on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call Dagger function to build and publish to ghcr.io
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          module: github.com/daggerverse/dagger-ghcr-demo@v0.1.5
          args: >-
            build-and-push
            --registry=ghcr.io
            --image-name=${{ github.repository }}
            --username=${{ github.actor }}
            --password=env://DOCKER_PASSWORD
            --build-context=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
