name: Dagger Test
on:
  workflow_dispatch:

jobs:
  dagger-job:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Dagger Pipeline
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          version: 0.18.14
          module: github.com/daggerverse/dagger-ghcr-demo@v0.1.5
          args: |
            build-and-push
            --registry=ghcr.io
            --image-name=ghcr.io/${GITHUB_ACTOR}/dagger-test
            --username=env://USERNAME
            --password=env://DOCKER_PASSWORD
            --build-context=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}



